# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
                ('short', models.CharField(max_length=20)),
                ('created', models.DateTimeField()),
                ('clicks_count', models.PositiveIntegerField()),
            ],
        ),
    ]
