# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0004_auto_20160712_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
