# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_auto_20160713_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='short',
            new_name='short_url',
        ),
    ]
