# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0006_auto_20160714_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterIndexTogether(
            name='link',
            index_together=set([('clicks_count', 'created')]),
        ),
    ]
